/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated";

/*
 * Type representing codename of 'Default project language' language
 */
export type DefaultProjectLanguageLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Default project language' language
 */
export function isDefaultProjectLanguageLanguageCodename(
  value: string | undefined | null,
): value is DefaultProjectLanguageLanguageCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultProjectLanguageLanguageCodename);
}
