/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

export * from "./collections/default-collection.generated";
export * from "./languages/default-project-language-language.generated";
export * from "./system/collections.generated";
export * from "./system/elements.generated";
export * from "./system/languages.generated";
export * from "./system/main.system.generated";
export * from "./system/snippets.generated";
export * from "./system/taxonomies.generated";
export * from "./system/types.generated";
export * from "./system/workflows.generated";
export * from "./taxonomies/event-topic.generated";
export * from "./taxonomies/event-type.generated";
export * from "./types/article.generated";
export * from "./types/event.generated";
export * from "./types/landing-page.generated";
export * from "./types/video.generated";
export * from "./workflows/default-workflow.generated";
