/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated";
import type { LanguageCodenames } from "../system/languages.generated";
import type { CoreType, TypeCodenames } from "../system/types.generated";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated";

/*
 * Type representing codename of 'Article' type
 */
export type ArticleTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article">;

/*
 * Typeguard for codename of 'Article' type
 */
export function isArticleTypeCodename(value: string | undefined | null): value is ArticleTypeCodename {
  return typeof value === "string" && value === ("article" satisfies ArticleTypeCodename);
}

/*
 * Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 * External Id: article
 */
export type ArticleType = IContentItem<
  {
    /*
     * Title
     *
     * Codename: title
     * Id: ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc
     * External Id: article_default_title_element
     * Type: text
     * Required: true
     */
    readonly title: Elements.TextElement;

    /*
     * Introduction
     *
     * Codename: introduction
     * Id: c3fc1a88-5577-5130-b0aa-b1837c009ba6
     * External Id: article_default_introduction_element
     * Type: text
     * Required: true
     */
    readonly introduction: Elements.TextElement;

    /*
     * Image
     *
     * Codename: image
     * Id: 8c501358-d0f7-5959-95bd-2991f1215e33
     * External Id: article_default_image_element
     * Type: asset
     * Required: true
     */
    readonly image: Elements.AssetsElement;

    /*
     * Body Copy
     *
     * Codename: body_copy
     * Id: 0747fb13-7383-59fe-bf64-2bab6d384279
     * External Id: article_default_body_copy_element
     * Type: rich_text
     * Required: true
     */
    readonly body_copy: Elements.RichTextElement<CoreType>;

    /*
     * Publish Date
     *
     * Codename: publish_date
     * Id: abdf08ea-55f0-5460-96e0-391f7471c7e9
     * External Id: article_default_publish_date_element
     * Type: date_time
     * Required: true
     */
    readonly publish_date: Elements.DateTimeElement;
  },
  ArticleTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Article
 */
export type ArticleTypeElementCodenames = "title" | "introduction" | "image" | "body_copy" | "publish_date";

/*
 * Type guard for Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 * External Id: article
 */
export function isArticleType(item: IContentItem | undefined | null): item is ArticleType {
  return item?.system.type === ("article" satisfies ArticleTypeCodename);
}
