/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated";
import type { LanguageCodenames } from "../system/languages.generated";
import type { TypeCodenames } from "../system/types.generated";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated";

/*
 * Type representing codename of 'Video' type
 */
export type VideoTypeCodename = keyof Pick<Record<TypeCodenames, null>, "video">;

/*
 * Typeguard for codename of 'Video' type
 */
export function isVideoTypeCodename(value: string | undefined | null): value is VideoTypeCodename {
  return typeof value === "string" && value === ("video" satisfies VideoTypeCodename);
}

/*
 * Video
 *
 * Id: 5b2003c5-fe38-5a6e-a21b-a7b2f5ee0ddb
 * Codename: video
 * External Id: video
 */
export type VideoType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 0bd216b2-4975-50f9-832e-6e2c6c5d1bf9
     * External Id: video_default_headline_element
     * Type: text
     * Required: false
     */
    readonly headline: Elements.TextElement;

    /*
     * Description
     *
     * Codename: description
     * Id: c454e463-2c85-57a2-aec8-e399a392b229
     * External Id: video_default_description_element
     * Type: text
     * Required: false
     */
    readonly description: Elements.TextElement;

    /*
     * Video Link
     *
     * Codename: video_link
     * Id: 09573446-747b-572e-af77-9cbf359bcdad
     * External Id: video_default_video_link_element
     * Type: text
     * Required: true
     */
    readonly video_link: Elements.TextElement;

    /*
     * Caption
     *
     * Codename: caption
     * Id: c3054bab-604f-5d9d-bf1f-06c87cd5b15e
     * External Id: video_default_caption_element
     * Type: text
     * Required: false
     */
    readonly caption: Elements.TextElement;

    /*
     * Autoplay
     *
     * Codename: autoplay
     * Id: 21250a1b-2eff-52cc-89b2-a44a2bab8b93
     * External Id: video_default_autoplay_element
     * Type: multiple_choice
     * Required: false
     */
    readonly autoplay: Elements.MultipleChoiceElement<VideoTypeAutoplayMultipleChoiceOptions>;
  },
  VideoTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Video
 */
export type VideoTypeElementCodenames =
  | "headline"
  | "description"
  | "video_link"
  | "caption"
  | "autoplay";

/*
 * Type guard for Video
 *
 * Id: 5b2003c5-fe38-5a6e-a21b-a7b2f5ee0ddb
 * Codename: video
 * External Id: video
 */
export function isVideoType(item: IContentItem | undefined | null): item is VideoType {
  return item?.system.type === ("video" satisfies VideoTypeCodename);
}

export type VideoTypeAutoplayMultipleChoiceOptions = "true" | "false";
