/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated";

/*
 * Type representing codename of 'Default' workflow
 */
export type DefaultWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Default' workflow
 */
export function isDefaultWorkflowCodename(value: string | undefined | null): value is DefaultWorkflowCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultWorkflowCodename);
}

/*
 * Array of all workflow step codenames
 */
export const defaultWorkflowStepCodenames = ["draft", "published", "archived", "scheduled"] as const;

/*
 * Type representing all workflow step codenames
 */
export type DefaultWorkflowStepCodenames = (typeof defaultWorkflowStepCodenames)[number];

/*
 * Typeguard for workflow step codename
 */
export function isDefaultWorkflowStepCodename(value: string | undefined | null): value is DefaultWorkflowStepCodenames {
  return typeof value === "string" && (defaultWorkflowStepCodenames as readonly string[]).includes(value);
}
