/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
  "name",
  "image",
  "start_date",
  "end_date",
  "event_type",
  "event_topic",
  "description",
  "headline",
  "video_link",
  "caption",
  "autoplay",
  "subheadline",
  "hero_image",
  "body_copy",
  "featured_content",
  "title",
  "introduction",
  "publish_date",
] as const;

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
  return typeof value === "string" && (elementCodenames as readonly string[]).includes(value);
}
