/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { IDeliveryClient } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "./collections.generated";
import type { ElementCodenames } from "./elements.generated";
import type { LanguageCodenames } from "./languages.generated";
import type { TaxonomyCodenames } from "./taxonomies.generated";
import type { CoreType, TypeCodenames } from "./types.generated";
import type { WorkflowCodenames, WorkflowStepCodenames } from "./workflows.generated";

/*
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
  readonly collectionCodenames: CollectionCodenames;
  readonly contentItemType: CoreType;
  readonly contentTypeCodenames: TypeCodenames;
  readonly elementCodenames: ElementCodenames;
  readonly languageCodenames: LanguageCodenames;
  readonly taxonomyCodenames: TaxonomyCodenames;
  readonly workflowCodenames: WorkflowCodenames;
  readonly workflowStepCodenames: WorkflowStepCodenames;
};

/*
 * Typed delivery client. Use this instead of 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>;
