/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = [] as const;

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number];

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
  return typeof value === "string" && (snippetCodenames as readonly string[]).includes(value);
}
