/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { ArticleType } from "../types/article.generated";
import type { EventType } from "../types/event.generated";
import type { LandingPageType } from "../types/landing-page.generated";
import type { VideoType } from "../types/video.generated";

/*
 * Array of all type codenames
 */
export const typeCodenames = ["event", "video", "landing_page", "article"] as const;

/*
 * Type representing all type codenames
 */
export type TypeCodenames = (typeof typeCodenames)[number];

/*
 * Typeguard for type codename
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
  return typeof value === "string" && (typeCodenames as readonly string[]).includes(value);
}

/*
 * Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
 */
export type CoreType = EventType | VideoType | LandingPageType | ArticleType;

/*
 * Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
 */
export type CodenameTypeMapping = {
  readonly event: EventType;
  readonly video: VideoType;
  readonly landing_page: LandingPageType;
  readonly article: ArticleType;
};

/*
 * Helper type that returns type based on the codename of type.
 */
export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping
  ? CodenameTypeMapping[TTypeCodename]
  : CoreType;
