/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated";

/*
 * Type representing codename of 'Event Type' taxonomy
 */
export type EventTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "event_type">;

/*
 * Typeguard for codename of 'Event Type' taxonomy
 */
export function isEventTypeTaxonomyCodename(value: string | undefined | null): value is EventTypeTaxonomyCodename {
  return typeof value === "string" && value === ("event_type" satisfies EventTypeTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const eventTypeTaxonomyTermCodenames = ["seminar", "webinar", "workshop"] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type EventTypeTaxonomyTermCodenames = (typeof eventTypeTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isEventTypeTaxonomyTermCodename(
  value: string | undefined | null,
): value is EventTypeTaxonomyTermCodenames {
  return typeof value === "string" && (eventTypeTaxonomyTermCodenames as readonly string[]).includes(value);
}
