/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated";

/*
 * Type representing codename of 'Event Topic' taxonomy
 */
export type EventTopicTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "event_topic">;

/*
 * Typeguard for codename of 'Event Topic' taxonomy
 */
export function isEventTopicTaxonomyCodename(value: string | undefined | null): value is EventTopicTaxonomyCodename {
  return typeof value === "string" && value === ("event_topic" satisfies EventTopicTaxonomyCodename);
}

/*
 * Array of all taxonomy term codenames
 */
export const eventTopicTaxonomyTermCodenames = ["nutrition", "physical_fitness", "preventative_care"] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type EventTopicTaxonomyTermCodenames = (typeof eventTopicTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isEventTopicTaxonomyTermCodename(
  value: string | undefined | null,
): value is EventTopicTaxonomyTermCodenames {
  return typeof value === "string" && (eventTopicTaxonomyTermCodenames as readonly string[]).includes(value);
}
