/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: c909ced2-86e2-0094-c0bf-bc35576d7a0f
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated";

/*
 * Type representing codename of 'Default' collection
 */
export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Default' collection
 */
export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultCollectionCodename);
}
